In [38]:
import cv2
import pandas as pd

img = cv2.imread('colorimage.jpg')

clicked = False
r = g = b = xpos = ypos= 0

index = ["color", "colorname", "hex", "R", "G", "B"]
df = pd.read_csv('colors.csv', names = index, header = None)
df

                    color              colorname      hex    R    G    B
0      air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
1     air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
2    air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
3         alabama_crimson        Alabama Crimson  #a32638  163   38   56
4              alice_blue             Alice Blue  #f0f8ff  240  248  255
..                    ...                    ...      ...  ...  ...  ...
860         yellow_orange          Yellow Orange  #ffae42  255  174   66
861        yellow_process       Yellow (Process)  #ffef00  255  239    0
862            yellow_ryb           Yellow (Ryb)  #fefe33  254  254   51
863                zaffre                 Zaffre  #0014a8    0   20  168
864     zinnwaldite_brown      Zinnwaldite Brown  #2c1608   44   22    8

[865 rows x 6 columns]

In [39]:
df.head()

                  color              colorname      hex    R    G    B
0    air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
1   air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
2  air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
3       alabama_crimson        Alabama Crimson  #a32638  163   38   56
4            alice_blue             Alice Blue  #f0f8ff  240  248  255

In [40]:
# Creating a window and setting an call back event

def draw_function(event, x,y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        global b, g, r, xpos, ypos, clicked
        clicked = True
        xpos = x
        ypos = y
        b,g,r = img[y,x]
        b = int(b)
        g = int(g)
        r = int(r)
        

cv2.namedWindow("Image")
cv2.setMouseCallback('Image', draw_function)

In [41]:
# Distance calculation to get color name

def colorName(R, G, B):
    minimum = 20000
    for i in range(len(df)):
        d = abs(R - int(df.loc[i,"R"])) + abs(G - int(df.loc[i,"G"])) + abs(B - int(df.loc[i,"B"]))
        if (d<=minimum):
            minimum = d
            cname = df.loc[i,"colorname"]
    return cname

In [42]:
# Displaying image on the window

while(1):
    cv2.imshow("Image",img)
    if (clicked):
        cv2.rectangle(img, (30,30), (750,60), (b,g,r), -1)
        text = colorName(r,g,b) + ' R=' + str(r) + ' G=' + str(g) + ' B=' + str(b)
        cv2.putText(img, text, (52,52), 3,0.8,(255,255,255), 2, cv2.LINE_AA)
        if (r+g+b>=600):
            cv2.putText(img, text, (30,30), 3,0.8,(0,0,0), 2, cv2.LINE_AA)
        clicked = False
    if cv2.waitKey(20) & 0xFF == 27:
        break
cv2.destroyAllWindows()